### ISSUE TITLE
Problem With Firefox and Edge

### ISSUE THREAD

**Issue by stefanodanieli** [FriendsOfTYPO3/rtehtmlarea#47] opened 2021-06-14 12:35 UTC
Hi,
 would like to report the following bug.
I have installed the extension rtehtmlarea.

I want to edit a standard text element. When the wysiwyg editor is shown, i can see the following error :

Uncaught TypeError: Cannot read property 'documentElement' of null
at Iframe.initializeIframe (Iframe.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:202)
at Iframe.render (Iframe.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:57)
at Framework.render (Framework.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:75)
at new Framework (Framework.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:45)
at Editor.createFramework (Editor.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:189)
at Editor.generate (Editor.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:175)
at Editor.js?bust=cb447f8edb30784c674c7418ad59e08d5e85f7c9:179

I check
typo3\sysext\rtehtmlarea\Resources\Public\JavaScript\HTMLArea\Editor\Iframe.js
where the problem seems to be located :

At row 201 :

// WebKit
} else if (UserAgent.isWebKit && (!iframe.contentDocument.documentElement || !iframe.contentDocument.body)) {
window.setTimeout(function () {
self.initializeIframe();
}, 50);

Seems iframe.contentDocument is not initialized (eg :is null)

Tested in TYPO3 7.6.32
Rtehtmlarea version 7.6.32 and 8.7.0
Chrome version 91.0.4472.101 (64 Bit)

**Comment by m41r** [comment] 2021-06-14 14:25
duplicate of #46

**Closed as completed** 2021-06-15 13:16 UTC
Labels: duplicate
