### ISSUE TITLE
typo3 backend gets translated into syslang but backend text editor is still english

### ISSUE THREAD

**Issue by novawebstar** [FriendsOfTYPO3/rtehtmlarea#25] opened 2019-01-15 14:37 UTC
After updating form typ3 version 6.7 to 7.6 the backend-editor is still working but does not get translated. All buttons and dialogs are still englisch.

The l10n files for the target language (german) are updated and in `typo3conf/l10n/de/rtehtmlarea`
`static_info_tables` and `static_info_tables_de` are installed.

Page TSconfig is:

```
# ***************************************************************************************
# "Typical" Page TSconfig for htmlArea RTE and Classic RTE
#
# Sets Page TSConfig with most commonly used features representing a good start for typical sites.
# ***************************************************************************************

	## Define labels and styles to be applied to class selectors in the interface of the RTE
	## The examples included here make partial re-use of color scheme and frame scheme from CSS Styled Content extension
RTE.classes {
	align-left {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_tooltips.xlf:justifyleft
		value = text-align: left;
	}
	align-center {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_tooltips.xlf:justifycenter
		value = text-align: center;
	}
	align-right {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_tooltips.xlf:justifyright
		value = text-align: right;
	}
	csc-frame-frame1 {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:frame-frame1
		value = background-color: #EDEBF1; border: 1px solid #333333;
	}
	csc-frame-frame2 {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:frame-frame2
		value = background-color: #F5FFAA; border: 1px solid #333333;
	}
	important {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:important
		value = color: #8A0020;
	}
	name-of-person {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:name-of-person
		value = color: #10007B;
	}
	detail {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:detail
		value = color: #186900;
	}
	component-items {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:component-items
		value = color: #186900;
	}
	action-items {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:action-items
		value = color: #8A0020;
	}
	component-items-ordered {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:component-items
		value = color: #186900;
	}
	action-items-ordered {
		name = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_contentcss.xlf:action-items
		value = color: #8A0020;
	}
}

	## Anchor classes configuration for use by the anchor accesibility feature
RTE.classesAnchor {
	externalLink {
		class = external-link
		type = url
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:external_link_titleText
	}
	externalLinkInNewWindow {
		class = external-link-new-window
		type = url
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:external_link_new_window_titleText
	}
	internalLink {
		class = internal-link
		type = page
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:internal_link_titleText
	}
	internalLinkInNewWindow {
		class = internal-link-new-window
		type = page
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:internal_link_new_window_titleText
	}
	download {
		class = download
		type = file
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:download_titleText
	}
	mail {
		class = mail
		type = mail
		titleText = LLL:EXT:rtehtmlarea/Resources/Private/Language/locallang_accessibilityicons.xlf:mail_titleText
	}
	pfeil {
		class = pfeil
		type = page
		titleText = LLL:EXT:rtehtmlarea/res/accessibilityicons/locallang.xml:internal_link_titleText
	}
}

	## Default RTE configuration
RTE.default {

		## Markup options (htmlArea RTE only)
	enableWordClean = 1
	removeTrailingBR = 1
	removeComments = 1
	removeTags = center, font, o:p, sdfield, strike, u
	removeTagsAndContents = link, meta, script, style, title

		## Toolbar options
		## The TCA configuration may add buttons to the toolbar
		## The following buttons are specific to Classic RTE: class
		## The following buttons are specific to htmlArea RTE: blockstylelabel, blockstyle, textstylelabel, textstyle,
		##		insertcharacter, findreplace, removeformat, toggleborders, tableproperties,
		##		rowproperties, rowinsertabove, rowinsertunder, rowdelete, rowsplit,
		##		columninsertbefore, columninsertafter, columndelete, columnsplit,
		##		cellproperties, cellinsertbefore, cellinsertafter, celldelete, cellsplit, cellmerge
	showButtons (
		class, blockstylelabel, blockstyle, textstylelabel, textstyle,
		formatblock, bold, italic, subscript, superscript,
		orderedlist, unorderedlist, outdent, indent, textindicator,
		insertcharacter, link, table, findreplace, chMode, removeformat, undo, redo, about,
		toggleborders, tableproperties, inserttag,
		rowproperties, rowinsertabove, rowinsertunder, rowdelete, rowsplit,
		columninsertbefore, columninsertafter, columndelete, columnsplit,
		cellproperties, cellinsertbefore, cellinsertafter, celldelete, cellsplit, cellmerge
	)

		## More toolbar options (htmlArea RTE only)
	keepButtonGroupTogether = 1

		## Enable status bar (htmlArea RTE only)
	showStatusBar =  1

		## Hide infrequently used paragraph types in the paragraph type selector (formatblock button)
	buttons.formatblock.removeItems = pre,address



		## List all class selectors that are allowed on the way to the database
	proc.allowedClasses (
		external-link, external-link-new-window, internal-link, internal-link-new-window, download, mail,
		align-left, align-center, align-right, align-justify,
		csc-frame-frame1, csc-frame-frame2,
		component-items, action-items,
		component-items-ordered, action-items-ordered,
		important, name-of-person, detail,
		indent
	)

		## buttons.blockstyle.tags.div.allowedClasses, buttons.blockstyle.tags.table.allowedClasses, buttons.blockstyle.tags.td.allowedClasses, buttons.link.properties.class.allowedClasses, buttons.textstyle.tags.span.allowedClasses
		## Classic RTE: Specify the list of class selectors that should be presented in the RTE interface:
		## htmlArea RTE: Restrict the list of class selectors presented by the RTE to the following:
	buttons.blockstyle.tags.div.allowedClasses (
		align-left, align-center, align-right,
		csc-frame-frame1, csc-frame-frame2
	)
	buttons.blockstyle.tags.table.allowedClasses = csc-frame-frame1, csc-frame-frame2
	buttons.blockstyle.tags.td.allowedClasses = align-left, align-center, align-right
	buttons.link.properties.class.allowedClasses = external-link, external-link-new-window, internal-link, internal-link-new-window, download, mail
	buttons.textstyle.tags.span.allowedClasses = important, name-of-person, detail

		## Configuration of the anchor accessibility feature (htmlArea RTE only)
		## These classes should also be in the list of allowedClasses.
	classesAnchor = external-link, external-link-new-window, internal-link, internal-link-new-window, download, mail
	classesAnchor.default {
		page = internal-link
		url = external-link-new-window
		file = download
		mail = mail
	}

		## Configuration specific to the TableOperations feature (htmlArea RTE only)
		## Remove the following fieldsets from the table operations dialogs
	disableAlignmentFieldsetInTableOperations = 0
	disableSpacingFieldsetInTableOperations = 1
	disableColorFieldsetInTableOperations = 0
	disableLayoutFieldsetInTableOperations = 0
	disableBordersFieldsetInTableOperations = 1
		## Show borders on table creation
	buttons.toggleborders.setOnTableCreation = 1

		## Configuration specific to the bold and italic buttons (htmlArea RTE only)
		## Add hotkeys associated with bold and italic buttons
	buttons.bold.hotKey = b
	buttons.italic.hotKey = i
	buttons.inserttag.denyTags = a, abbr, abbreviation, address, b, big, blockquote, cite, code, div, em, fieldset, a, font, h1, h2, h3, h4, h5, h6, i, legend, li, ol, p, pre, q, small, span, strong, sub, sup, table, tt, ul
	
}
RTE.default.showButtons = *
RTE.default.proc {
                # tags die erlaubt / verboten sind
                allowTags = table, tbody, tr, th, td, h1, h2, h3, h4, h5, h6, div, p, br, span, ul, ol, li, re, blockquote, strong, em, b, i, u, sub, sup, strike, a, img, nobr, hr, tt, q, cite, abbr, abbreviation, center
                denyTags = font
 
                # br wird nicht zu p konvertiert
                dontConvBRtoParagraph = 1
 
                # tags sind erlaubt außerhalt von p, div
                allowTagsOutside = img,hr
}
	## front end RTE configuration for the general public (htmlArea RTE only)
RTE.default.FE < RTE.default
RTE.default.FE.showStatusBar = 0
#RTE.default.FE.hideButtons = chMode, blockstyle, textstyle, underline, strikethrough, subscript, superscript, lefttoright, righttoleft, left, center, right, justifyfull, table, inserttag, findreplace, removeformat, copy, cut, paste
RTE.default.FE.FE >
RTE.default.FE.userElements >
RTE.default.FE.userLinks >
RTE.default.showButtons := addToList(image)
RTE.default.proc.allowTags := addToList(tooltip)
```

**Comment by liayn** [comment] 2020-03-24 22:54
closing as duplicate of #33

**Closed as completed by liayn** 2020-03-24 22:54 UTC
