### ISSUE TITLE
Regression with Chrome 73 in Typo3 7.6.32 

### ISSUE THREAD

**Issue by foppelfb** [FriendsOfTYPO3/rtehtmlarea#26] opened 2019-02-27 11:34 UTC
Effect of the Problem:
When viewed in a Chrome 73 (MacOS Version 73.0.3683.46 (Official Build) beta (64-bit)) the RTE displays an empty raw HTML Document.
The Javascript Console does not throw an error, last message pertaining the RTE is:
[HTMLArea.Editor::onFrameworkReady]: Editor ready.

Chrome 72 works as expected, so do recent Firefox and Safari

**Comment by ohader** [comment] 2019-03-13 09:43
Confirmed in TYPO3 v8 as well...

**Comment by pschriner** [comment] 2019-03-13 10:38
![Screenshot_2019-03-13_11-35-55](https://user-images.githubusercontent.com/2487207/54272665-69878700-4584-11e9-8e4f-a5f9bb2aba95.png)

For some reason chrome never loads the resources

When debugging (chrome://net-internals) I get 

{"params":{"description":"","error_code":"8 (CANCEL)","stream_id":863},"phase":0,"source":{"id":13650,"type":9},"time":"112707070","type":191},

Which is not really helpful

**Comment by kkugelmann** [comment] 2019-03-13 10:50
+1 here

**Comment by Geddo** [comment] 2019-03-13 12:04
+1
Breaks my RTE on 6.2 LTS and 7.6 LTS
no problem with 8.7.24 so far

**Comment by amtmich** [comment] 2019-03-14 05:58
+1 - same in 6.2 LTS

**Comment by andreasberniczki** [comment] 2019-03-14 07:19
Same problem with 7.6 LTS

**Comment by bmack** [comment] 2019-03-14 07:50
Thanks for the reports. I will see how time fits to fix this for RTEHtmlArea + TYPO3 v8. However, this repository only supports RTEHtmlArea for TYPO3 v8 LTS, so any issues regarding TYPO3 Core 6.2 and 7.6 won't and can't be addressed here, as the code base of the extension has changed since TYPO3 6.2/v7 (e.g. no ExtJS anymore).

If you have an active ELTS for TYPO3 v6.2/v7, there is a fix underway for the included RTEHtmlArea as well AFAIK. If you don't have ELTS, now is a good time to evaluate this https://typo3.com/products/extended-support.

**Comment by guppy42** [comment] 2019-03-14 10:14
To fix it for chrome 73:

Open the editor file:
for 6.2 it's /typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js 
for LTS 7 it's /typo3/sysext/rtehtmlarea/Resources/Public/JavaScript/HTMLArea/Editor/Editor.js

locate the line that says;
```
src: UserAgent.isGecko ? 'javascript:void(0);' : (UserAgent.isWebKit ? 'javascript: \'' + Util.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')
```

and change it to 
```
src: UserAgent.isGecko ? 'javascript:void(0);' : (UserAgent.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')
```

That's it - 6.2 seems to automatically notice the file has changed and creates a new merged file containing the change.

In 7.2 the file gets served with `?bust=.....` meaning if your server asks clients to cache JS for x days it will be a while before the change reaches them.

Any idea how I can forcibly change this bust value?

**Comment by thegass** [comment] 2019-03-14 10:27
8.7 picks up the change instant. 
fix seems to work for 8.7

**Comment by andreaskienast** [comment] 2019-03-14 10:31
Many thanks to @guppy42, I was fiddling at the same line and wondered what happens here. I will create a PR for this.

**Comment by guppy42** [comment] 2019-03-14 10:40
Seems the only way to change the `?bust=` is to either go into development mode or alter the typo3 version
TS_7/typo3/sysext/core/Classes/Core/SystemEnvironmentBuilder.php:88:        define('TYPO3_version', '7.6.32');

should be safe, but do so at your own peril ;)

**Comment by kevinlieser** [comment] 2019-03-14 10:51
Worked – thanks a lot!

**Comment by hkarvasonis** [comment] 2019-03-14 11:02
Thanks a lot for the fix! That worked as expected.

**Comment by amtmich** [comment] 2019-03-15 06:21
@guppy42 seems like this does not work for TYPO3 6.2. The code mentioned by you is not present in  /typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js or anywhere else. Does anyone manage to fix that in TYPO3 6.2 ?

**Closed as completed** 2019-03-15 07:01 UTC

**Comment by stigfaerch** [comment] 2019-03-18 09:45
> To fix it for chrome 73:
> 
> Open the editor file:
> for 6.2 it's /typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js
> for LTS 7 it's /typo3/sysext/rtehtmlarea/Resources/Public/JavaScript/HTMLArea/Editor/Editor.js
> 
> locate the line that says;
> 
> ```
> src: UserAgent.isGecko ? 'javascript:void(0);' : (UserAgent.isWebKit ? 'javascript: \'' + Util.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')
> ```

Regarding 6.2 - the htmlarea.js is very different from the Editor.js file in LTS 7.
I cannot find the line mentioned, or anything that resembles for that matter. The 6.2 version seems to be ExtJs based.

**Comment by amtmich** [comment] 2019-03-18 09:52
Yes - that file is little different from the one in 7.x. You need to patch that line https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js#L2187 and change it to
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html')`

**Comment by stigfaerch** [comment] 2019-03-18 10:10
> Yes - that file is little different from the one in 7.x. You need to patch that line https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_6-2/typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js#L2187 and change it to
> `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html')`

Thanks! I also found it and hurried to deleted my post, but you were to quick and managed to answer me before it was gone :-)

I changed to this instead (according to the fix in issue #31 )
```src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? (Ext.isChrome ? 'about:blank;' : 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' ): HTMLArea.editorUrl + 'popups/blank.html')```

**Comment by erthi16** [comment] 2019-03-18 13:16
Hello to all!

I've tested successfully with my TYPO3 ver. 7 but with my version 6.2.40, nothing works... Is it possible to remove browser detection or at least the Chrome detection? Is it related to the browser signature?
Thank you all for your help!

Eric Thibault

**Comment by slimco** [comment] 2019-03-19 12:21
Thanks! For my Typo3 6.2 works rewrite code to
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html')`

original code was:
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`

**Comment by susannemoog** [comment] 2019-03-19 16:59
FYI https://typo3.com/blog/typo3-7635-and-6241-elts-released

**Comment by Boa2** [comment] 2019-03-20 12:18
> I changed to this instead (according to the fix in issue #31 )
> `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? (Ext.isChrome ? 'about:blank;' : 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' ): HTMLArea.editorUrl + 'popups/blank.html')`

How would this line look for Typo3 7? Like so?
`src: UserAgent.isGecko ? 'javascript:void(0);' : (UserAgent.isWebKit ? (UserAgent.isChrome ? 'about:blank;' : 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' ): HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')`

or like so (found here: https://typo3.toaster-schwerin.de/typo3_german/2019_03/msg00035.html):
`src: UserAgent.isGecko ? 'javascript:void(0);' : (UserAgent.isWebKit ? (UserAgent.isChrome ? 'about:blank;' : 'javascript: \'' + Util.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' ): HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')`

**Comment by guppy42** [comment] 2019-03-20 14:49
@Boa2 

you could just look at the diff for #31 : https://github.com/FriendsOfTYPO3/rtehtmlarea/pull/31/commits/02cc2beeb6069d8726f8120ffd82eb890c2c469e

**Comment by Boa2** [comment] 2019-03-20 15:07
> 
> 
> @Boa2
> 
> you could just look at the diff for #31 : [02cc2be](https://github.com/FriendsOfTYPO3/rtehtmlarea/commit/02cc2beeb6069d8726f8120ffd82eb890c2c469e)

Thanks. This works.

**Comment by baden32** [comment] 2019-03-26 13:13
Is there a chance that the problem will be fixed with Chrome version 74 or do we definitely need to patch rtehtmlarea js files?

**Comment by runningnet** [comment] 2019-03-26 15:10
This work for me in 4.7 (i know it is old) 
File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line about: 2214

I change this:
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`

with that:
`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html')
`

**Comment by erthi16** [comment] 2019-03-26 15:26
The 6.2.41 version worked on our second server... we are redoing the first one and retesting.

**Comment by doctotto** [comment] 2019-03-26 16:04
This work for me in 4.5.40 (i know it is old)²
File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line : 2224
from:
src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')

to:
src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? (Ext.isChrome ? 'about:blank;' : 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'') : HTMLArea.editorUrl + 'popups/blank.html')

**Comment by crealistiques** [comment] 2019-03-27 18:15
I can confirm. For me an update to latest ELTS version 6.2.41 worked as a fix!

**Comment by erthi16** [comment] 2019-03-27 19:10
Message from doctotto (and tested on at least one site in our ecosystem):

This work for me in 4.5.40 (i know it is old)²
File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line : 2224
from:
src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: '' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + ''' : HTMLArea.editorUrl + 'popups/blank.html')
to:
src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? (Ext.isChrome ? 'about:blank;' : 'javascript: '' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + ''') : HTMLArea.editorUrl + 'popups/blank.html')

**Comment by cactysman** [comment] 2019-03-28 16:12
Would be nice if someone hit up the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and created a new issue - or contributed to one if one already exists that might be related to this problem.

This way we're not just spinning up workarounds but they can actually investigate and resolve that issue.

**Comment by Turbotailz** [comment] 2019-03-28 22:09
This is also a problem in v4 - don't ask, client won't pay to upgrade

**Comment by andreaskienast** [comment] 2019-03-29 07:34
> Would be nice if someone hit up the [Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/list) and created a new issue - or contributed to one if one already exists that might be related to this problem.
> 
> This way we're not just spinning up workarounds but they can actually investigate and resolve that issue.

I don't think this is a bug in Blink rendering engine, but a security change that breaks our legacy code base, which is absolutely fine.
I don't consider the fix(es) a workaround, but necessary changes to let HtmlArea work with the latest versions of the rendering engine.

**Comment by wolfgang007** [comment] 2019-04-01 10:43
Is there a fix for 8.7 already?

**Comment by mmasmoudi** [comment] 2019-04-02 06:36
I'm looking for a fix for Typo3 8.7 too.

**Comment by andreaskienast** [comment] 2019-04-02 06:54
You should be able to update the extension either from TER or packagist.

**Comment by sevenflip** [comment] 2019-04-02 07:22
Link to the chromium bugreport:
https://bugs.chromium.org/p/chromium/issues/detail?id=946984

Add ⭐️ to push it (sign in & click in the top left corner)

**Comment by mmasmoudi** [comment] 2019-04-02 07:23
@andreasfernandez Yes i did that already, i upgraded to version 8.7.2 but this didn't resolve the problem.
--

**Comment by andreaskienast** [comment] 2019-04-02 07:39
@mmasmoudi I fail to reproduce the issue after upgrading to 8.7.2. Did you clear your browser caches after installing the update?

**Comment by mmasmoudi** [comment] 2019-04-02 07:47
@andreasfernandez Sorry, forget clear cache from browser after the TER update, problem is resolved, Thank you !

**Comment by Kai-Petersen** [comment] 2019-04-02 14:02
After installing the Patch i can use the RTE, but it's not possible to save an empty RTE. Each time i save the content element, a linebreak is added too the textarea an in the frontend i get an empty p tag for every linebreak. In WYSIWYG-MODE, the linebreaks not shown, only in TEXT-MODUS they are visible.

**Comment by tommysack** [comment] 2019-04-04 10:13
> This work for me in 4.7 (i know it is old)
> File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line about: 2214
> 
> I change this:
> `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`
> 
> with that:
> `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html') `

@runningnet Hy, In my version (4.5 very very old, i know) I have replaced the code in htmlarea.js
but it returns every time the same old code in typo3temp/compressor/htmlarea_cumulative_***_compressed-***.js
Have you delete some files after the fix? Also if I delete the compressed file it create the same htmlarea_cumulative_***_compressed-***.js with old code..

**Comment by doctotto** [comment] 2019-04-04 10:53
> > This work for me in 4.7 (i know it is old)
> > File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line about: 2214
> > I change this:
> > `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`
> > with that:
> > `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html') `
> 
> @runningnet Hy, In my version (4.5 very very old, i know) I have replaced the code in htmlarea.js
> but it returns every time the same old code in typo3temp/compressor/htmlarea_cumulative_***_compressed-***.js Have you delete some files after the fix? Also if I delete the compressed file it create the same htmlarea_cumulative_***_compressed-***.js with old code..

Yes you should clear the RTE Cache (backend top right lighting bolt icons)

**Comment by tommysack** [comment] 2019-04-09 14:40
> > > This work for me in 4.7 (i know it is old)
> > > File: typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js Line about: 2214
> > > I change this:
> > > `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`
> > > with that:
> > > `src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'popups/blank.html') `
> > 
> > 
> > @runningnet Hy, In my version (4.5 very very old, i know) I have replaced the code in htmlarea.js
> > but it returns every time the same old code in typo3temp/compressor/htmlarea_cumulative_***_compressed-***.js Have you delete some files after the fix? Also if I delete the compressed file it create the same htmlarea_cumulative_***_compressed-***.js with old code..
> 
> Yes you should clear the RTE Cache (backend top right lighting bolt icons)

Ok thanks, it works

**Comment by BeSchAu** [comment] 2019-06-05 13:59
Any chance to get this problem fixed in version 4.2.8?
We have this problem on two remaining websites which currently get redesigned.
But i have to get it working for about half an year.

Can anyone tell me which code has to be replaced?

**Comment by BeSchAu** [comment] 2019-06-06 09:10
> This is also a problem in v4 - don't ask, client won't pay to upgrade

@Turbotailz
Did you get it fixed for this version? We have version 4.2.8 and the fix doenst work for this version :(

**Comment by Turbotailz** [comment] 2019-06-06 22:38
@BeSchAu can't remember, sorry. I no longer work for that agency.

**Comment by BeSchAu** [comment] 2019-06-07 05:34
@runningnet @erthi16 @guppy42 
Do you have any infos how to get this fixed in version 4.2.8?

**Comment by pisagatos** [comment] 2019-06-18 11:21
@BeSchAu 
> @runningnet @erthi16 @guppy42
> Do you have any infos how to get this fixed in version 4.2.8?

Try this line. I changed in Typo3 v. 4.3.3 and it works:
_\httpdocs\typo3\sysext\rtehtmlarea\htmlarea\htmlarea.js_

831 (Original) - : `iframe.setAttribute("src", (HTMLArea.is_opera?_typo3_host_url:"") + _editor_url + "popups/blank.html");`

831 (New line) + : `iframe.setAttribute("src", (HTMLArea.is_chrome? "javascript:void(0);" : (HTMLArea.is_safari? 'about:blank;' : _editor_url + 'popups/blank.html')));`

Remember clear _cache > Clear RTE cache_

**Comment by sheydin** [comment] 2019-07-04 11:32
TYPO3 7.6.32 & Chrome 75 here. Tried every solution and deleted Cached on each try. Editor still outputs Doctype and Console throws:
`[HTMLArea.CSS.Parser::parse]: The stylesheets could not be parsed. Reported error: Empty stylesheets array or missing linked stylesheets`

Please help.

**Comment by Norcoen** [comment] 2019-08-06 09:18
After updating safari the bug seems to be back under 7.6.38

**Comment by paul-keller** [comment] 2019-08-12 07:17
I can confirm problem with safari. And the chrome patch of course does not work for safari.

**Comment by franzkugelmann** [comment] 2019-08-16 05:56
please try the patch suggested by @julianstefanov in https://github.com/FriendsOfTYPO3/rtehtmlarea/pull/31#commitcomment-34496546

**Comment by luzernervogel** [comment] 2020-02-01 23:02
@guppy42 Thanks a lot! 

For me (TYPO3 6.2.31 / rtehtmlarea 6.2.0) it was the line 

`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'javascript: \'' + HTMLArea.htmlEncode(this.config.documentType + this.config.blankDocument) + '\'' : HTMLArea.editorUrl + 'popups/blank.html')`

and I changed it to 

`src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? 'about:blank;' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')`

That did it's job.

**Comment by constantin-iliescu** [comment] 2020-02-27 15:00
@crealistiques

> I can confirm. For me an update to latest ELTS version 6.2.41 worked as a fix!

Can you confirm this is working on Safari also?

**Comment by bernhardberger** [comment] 2020-03-24 19:15
This is still (or again?) an issue in Chrome Version 80.0.3987.149 (Official Build) (64-bit)...

**Comment by liayn** [comment] 2020-03-24 21:39
@bernhardberger I don't know (yet), but please be so kind and open a new issue with your problem and only reference closed issues. Thanks.
